image: alpine/latest
packages:
- texlive-xetex
- texlive-dvi
- ghostscript
- texmf-dist-pstricks
- texmf-dist-fontsextra
- texmf-dist-latexextra
sources:
- https://git.sr.ht/~sircmpwn/hare-specification
artifacts:
- hare-specification/specification.pdf
tasks:
- signoff: |
    cd hare-specification
    if [ "$BUILD_REASON" = "patchset" ]
    then
        if ! git log --format='%b' origin/master^^.. | grep 'Signed-off-by' >/dev/null
        then
            echo "Patch missing Signed-off-by"
            exit 1
        fi
    fi
- build: |
    cd hare-specification
    make
