image: alpine/latest
packages:
- rsync
- texlive-xetex
- texlive-dvi
- ghostscript
- texmf-dist-pstricks
- texmf-dist-fontsextra
- texmf-dist-latexextra
secrets:
- 160a72cf-34d6-47b7-928b-c13b42b4d4f6
sources:
- https://git.sr.ht/~sircmpwn/hare-specification
artifacts:
- hare-specification/specification.pdf
tasks:
- signoff: |
    cd hare-specification
    if [ "$BUILD_REASON" = "patchset" ]
    then
        if ! git log --format='%b' origin/master^^.. | grep 'Signed-off-by' >/dev/null
        then
            echo "Patch missing Signed-off-by"
            exit 1
        fi
    fi
- build: |
    cd hare-specification
    make
    make # for the ToC
- upload: |
    if [ $BUILD_SUBMITTER != "git.sr.ht" ]
    then
        echo "Skipping upload for non-git.sr.ht build"
        exit
    fi
    cd hare-specification
    echo "StrictHostKeyChecking=no" >> ~/.ssh/config
    rsync -rP specification.pdf deploy@drewdevault.com:/var/www/harelang.org/
